name: test
on:
  workflow_call:
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - name: Setup .NET CLI
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore build from cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-build-${{ github.sha }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Run Key2Joy Tests
        run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat="lcov" /p:CoverletOutput="${{ github.workspace }}/coverage/lcov.info" /p:IncludeTestAssembly=true /p:ExcludeByFile="**/*.Designer.cs"
      - name: Coveralls for Key2Joy
        uses: coverallsapp/github-action@v2
